### ISSUE TITLE
Conflict resolving not well handled when generating conflicting routes for the same document

### ISSUE THREAD

**Issue by damienflament** [symfony-cmf/routing-auto-bundle#201]
When loading the PHPCR fixtures, one of the document have the same title in both translations. The generated routes are the same but the conflict resolver isn't called. Instead, I get an exception from Jackalope:         
                                      
 > [PHPCR\ItemExistsException]                                      
 > The node '/cms/routes' already has a child named 'sculptures''.

Fixture
-------

    $pages = $dm->find(Pages::class, '/cms/pages');
    
    $pageSculptures = new Page();
    $pageSculptures->setParentDocument($pages)
                   ->setTitle("Sculptures")
                   ->setContent(<<<__CONTENT__
    <p>Contenu...</p>
    __CONTENT__
    );
    $dm->persist($pageSculptures);
    $dm->bindTranslation($pageSculptures, 'fr');
    
    $pageSculptures->setParentDocument($pages)
                   ->setTitle("Sculptures")
                   ->setContent(<<<__CONTENT__
    <p>Content...</p>
    __CONTENT__
    );
    $dm->bindTranslation($pageSculptures, 'en');

    $dm->flush();

Routing configuration
----------------------

    App\Document\Page:
        definitions:
            view:
                uri_schema: /{title}
                defaults:
                    _controller: App:Page:view
        token_providers:
            title: [content_method, { method: getTitle }]

Exception trace
---------------

    () at /vendor/jackalope/jackalope/src/Jackalope/Node.php:419
    Jackalope\Node->addNode() at /vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/UnitOfWork.php:2339
    Doctrine\ODM\PHPCR\UnitOfWork->executeInserts() at /vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/UnitOfWork.php:2224
    Doctrine\ODM\PHPCR\UnitOfWork->commit() at /vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/DocumentManager.php:752
    Doctrine\ODM\PHPCR\DocumentManager->flush() at /app/DataFixtures/PHPCR/LoadPagesData.php:100
    App\DataFixtures\PHPCR\LoadPagesData->loadDocuments() at /app/DataFixtures/DataFixture.php:44
    App\DataFixtures\DataFixture->load() at /vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:121
    Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load() at /vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/PHPCRExecutor.php:69
    Doctrine\Common\DataFixtures\Executor\PHPCRExecutor->Doctrine\Common\DataFixtures\Executor\{closure}() at /vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/PHPCRExecutor.php:76
    Doctrine\Common\DataFixtures\Executor\PHPCRExecutor->execute() at /vendor/doctrine/phpcr-bundle/Command/LoadFixtureCommand.php:172
    Doctrine\Bundle\PHPCRBundle\Command\LoadFixtureCommand->execute() at /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
    Symfony\Component\Console\Command\Command->run() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:853
    Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:200
    Symfony\Component\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
    Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124

Note: The `App\DataFixtures\DataFixture` class implements `Doctrine\Common\DataFixtures\FixtureInterface`, checks for the _ObjectManager_ to be a _DocumentManager_ within the `FixtureInterface::load(ObjectManager $manager)` method then calls the `DataFixture::loadDocuments(DocumentManager $dm)` method.

Expected behavior
-------------------
The expected behavior is to fail with a `Symfony\Cmf\Component\RoutingAuto\ConflictResolver\Exception\ExistingUriException` exception.

**N.B**: As the conflict resolver isn't called, setting up to 'auto_increment' does not solve the issue.

**Comment by dbu** [comment]
phpcr fixtures is not going through the routing auto, if you just define
routes they will be loaded into the db directly. your fixtures would
need to talk to the routing auto services if you want it to act.

**Comment by damienflament** [comment]
@dbu : I don't create any routes manually. I just create some content documents.

After some debugging, I found that the routes are created in the `Symfony\Cmf\Bundle\RoutingAutoBundle\Doctrine\Phpcr\AutoRouteListener` when handling the _onFlush_ event.

**Comment by dbu** [comment]
ah sorry, then you are right, the auto route system should work the same as when content is created by some other means. could it be that the problem is that documents are not yet added to the document manager? or that the check whether the same thing already exists is done with a query instead of a check that works before flush is called?

**Comment by damienflament** [comment]
The _AutoRouteListener_ calls the `Symfony\Cmf\Component\RoutingAuto\AutoRouteManager::buildUriContextCollection()` method to make the routes for each "autorouteable" document. The _AutoRouteManager_ check for existing route matching the same URI by looking in the database (using the `Symfony\Cmf\Bundle\RoutingAutoBundle\Adapter\PhpcrOdmAdapter::findRouteForUri()` method).

The point is that when persisting a document for which the two translations use the same title (and may be available through the same URI, regarding my configuration), the first one isn't synchronized with the repository and is not accessible by the _DocumentManager_ when the second one is generated. So, the check failed and the _AutoRouteListener_ try to persist two routes located at the same nodepath.

**Comment by dbu** [comment]
that sounds plausible. if you want to contribute a fix, you can try to
follow the code path of findRouteForUri to see if it could use something
that is found even before flushing. or alternatively at least keep track
of what routes are being created in this process already, to dectect
conflicts.

**Comment by damienflament** [comment]
While trying to fix this issue, I think I understood the source of this issue. But it is related to the Routing Auto **Component**. So, I opened a new issue in the related repository.

See symfony-cmf/routing-auto#88.
