### ISSUE TITLE
How do you run the tests locally?

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/routing-auto-bundle#204]
I probably need some education here, what is `simple-phpunit` and why don't we include `phpunit` as a dependency?

I have been trying to run the tests, but even with `simple-phpunit` I get the following error:

```
16) Symfony\Cmf\Component\RoutingAuto\Tests\Unit\Adapter\PhpcrOdmAdapterTest::testFindRouteForUri
Error: Class 'Prophecy\Prophet' not found
```

Which seems to indicate that the version of PHPUnit included by `simple-phpunit` does not include prophecy.

**Comment by dantleech** [comment]
After looking, I guess `simple-phpunit` is used to be compatible with `PHP < 5.6` ? In which case I would like to drop it and revert to `^5.6|^6.0` if that makes sense. /cc @wouterj @dbu @damienflament

**Comment by damienflament** [comment]
`simple-phpunit` is [a configurable PHPUnit installation](http://symfony.com/doc/current/components/phpunit_bridge.html#modified-phpunit-script). The Prophecy bridge of PHPUnit is disabled by default but can be enabled as already done in the [Travis configuration file](https://github.com/symfony-cmf/routing-auto-bundle/blob/master/.travis.yml#L16). I added [a composer script to run the tests locally](https://github.com/symfony-cmf/routing-auto-bundle/pull/202/commits/3ce9e7c06ee3bd69bf692ec114acb7cb13415284?diff=split#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R51) the same way in my last PR.

As we don't rely on PHP <5.6 and this bundle is quite small (and don't need test run parallelization), it is not necessary. I don't replace it with a composer distributed version of PHPUnit in my PR as it's a Symfony bundle and that core bundles use `simple-php-unit`.

> revert to requiring phpunit `^5.6|^6.0`

PHPUnit 6.0 removed the deprecated `PHPUnit_Framework_TestCase` in favor of the namespaced `\PHPUnit\Framework\TestCase` class. If you don't want to modify the test files, using PHPUnit 5.7 should work as it supports PHP 7.0.
