### ISSUE TITLE
createAutoRoute third argument incompatible with interface

### ISSUE THREAD

**Issue by ConneXNL** [symfony-cmf/routing-auto-bundle#212]
I am getting an error on https://github.com/symfony-cmf/routing-auto-bundle/blob/master/src/Adapter/PhpcrOdmAdapter.php#L112 because the interface https://github.com/symfony-cmf/routing-auto/blob/master/src/AdapterInterface.php#L51 does not have a $locale variable.

Setting the third argument $locale = null fixes the problem.

Is this related to / since PHP 7.1.5 ?

**Comment by ElectricMaxxx** [comment]
@ConneXNL exactly. We try to use the latest RC of `routing-auto` here in the bundle, but are failing see #211 So the the RC's are not in sync anymore. Please use exaclty RC1/2 of routing-auto for now.
